// Shared by the downloadable storefront, live preview and public store page.
export const storefrontDesign = `
*{letter-spacing:0!important}html{scroll-padding-top:150px}body{background:var(--sf-bg);color:var(--sf-text)}
body[data-theme="clean"],body[data-theme="market"]{--sf-bg:#f6f7f9;--sf-text:#191b20;--sf-muted:#646972;--sf-border:#e0e3e8;--sf-surface:#fff;--sf-card:#fff}
body[data-theme="obsidian"]{--sf-bg:#101112;--sf-text:#f5f5f6;--sf-muted:#a8adb5;--sf-border:#303236;--sf-surface:#191b1e;--sf-card:#191b1e}
body[data-theme="aurora"]{--sf-bg:#f3f8f6;--sf-text:#122c26;--sf-muted:#556c65;--sf-border:#d7e5df;--sf-surface:#fff;--sf-card:#fff}
.wrap{width:min(1280px,calc(100% - 64px))}button,a,input{touch-action:manipulation}button:focus-visible,a:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid var(--sf-accent);outline-offset:4px}
.offer-bar{background:var(--sf-accent);color:var(--sf-accent-text);min-height:30px;font-size:11px}.level-badge{display:none}
.storefront-header{background:var(--sf-surface);border-color:var(--sf-border)}.storefront-nav{min-height:80px;flex-wrap:wrap;padding:14px 0}.storefront-brand strong{color:var(--sf-text);font-size:22px}.storefront-links a{color:var(--sf-muted)}.storefront-links a:hover{color:var(--sf-text)}.storefront-search input{background:var(--sf-bg);border-color:var(--sf-border);color:var(--sf-text);border-radius:8px}.storefront-search button{border-radius:5px}.storefront-nav-cta{margin:0}
.category-nav{background:var(--sf-surface);border-color:var(--sf-border)}.category-nav-inner{min-height:44px;overflow:auto;white-space:nowrap}.category-nav a,.category-nav a:first-child{color:var(--sf-muted)}.category-nav a:hover{color:var(--sf-text)}
.retail-hero{background:#16191c;padding:0;min-height:390px;isolation:isolate}.retail-hero:after{display:none}.hero-art{position:absolute;inset:0;z-index:-1;width:100%;height:100%;object-fit:cover;object-position:center 40%;opacity:.8}.retail-layout{display:block;padding:42px 0;min-height:390px}.retail-copy{max-width:630px;text-shadow:0 2px 14px #000}.retail-copy h1{font-size:52px;line-height:1.08;margin:16px 0;overflow-wrap:anywhere;color:#fff}.retail-copy p{font-size:16px;line-height:1.6;color:#fff;max-width:520px;background:#101214b8;padding:10px 14px;border-left:2px solid var(--sf-accent)}.retail-kicker{font-size:10px;border-radius:4px;text-shadow:none}.retail-actions{display:flex;gap:12px;flex-wrap:wrap}.retail-actions .cta{margin:0;text-shadow:none}.retail-actions .secondary-btn{background:#14171deb;text-shadow:none}.retail-cats,.retail-facts{display:none}.hero-feature{display:none}
.commerce-benefits{background:var(--sf-surface);border-color:var(--sf-border)}.benefit-row{background:transparent;grid-template-columns:repeat(4,minmax(0,1fr))}.benefit-row div{background:transparent;border-color:var(--sf-border);padding:20px 16px 20px 52px}.benefit-row b{color:var(--sf-text)}.benefit-row span{color:var(--sf-muted)}.benefit-icon{left:15px;top:21px;border:0;font-size:20px}
.collection-strip{background:var(--sf-bg);border-color:var(--sf-border);padding:30px 0}.strip-head h2,.section-title h2{color:var(--sf-text);font-size:24px}.strip-head p,.section-title p{color:var(--sf-muted);line-height:1.5}.collection-grid{display:flex;overflow:auto;gap:12px;padding:4px 0 12px;scroll-snap-type:x proximity}.collection-tile{flex:0 0 240px;background:var(--sf-surface);border-color:var(--sf-border);border-radius:8px;box-shadow:none;scroll-snap-align:start}.collection-tile span{color:var(--sf-text);overflow-wrap:anywhere}.collection-tile strong{color:var(--sf-muted)}
.section-title{margin:32px 0 20px}.filters{padding:4px 0 22px}.filter-btn{background:var(--sf-surface);border-color:var(--sf-border);color:var(--sf-muted);border-radius:6px;min-height:40px}.filter-btn.active{background:var(--sf-accent);color:var(--sf-accent-text);border-color:transparent}.grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}.card{border-color:var(--sf-border);background:var(--sf-card);border-radius:8px;box-shadow:0 4px 14px #00000005;transition:transform .22s,box-shadow .22s,border-color .22s}.card:hover{box-shadow:0 12px 32px #00000016;transform:translateY(-5px);border-color:var(--sf-accent)}.media{aspect-ratio:1;height:auto;background:var(--sf-surface)}.media img.logo-img{padding:18px;background:var(--sf-surface)}.media img.photo{object-fit:contain;padding:12px}.deal-badge{display:none}.card-body{padding:18px;gap:0}.meta-row{flex-wrap:wrap}.pill{background:var(--sf-bg);color:var(--sf-muted);font-size:10px;white-space:normal}.availability{display:none}.card h3{color:var(--sf-text);font-size:15px;line-height:1.5;min-height:45px;overflow-wrap:anywhere}.card p{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;color:var(--sf-muted);min-height:36px;font-size:12px}.card ul{display:none}.buy-row{border:0;margin-top:auto;padding-top:20px;display:block}.buy-row strong{font-size:24px;line-height:1.25;color:var(--sf-text)}.buy-row span{color:var(--sf-muted);margin-bottom:4px}.card-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:16px}.card-actions .secondary-btn{display:flex;background:transparent;border-color:var(--sf-border);color:var(--sf-text)}.card-actions button{font-size:12px;min-height:42px;padding:10px 6px;border-radius:6px}.card-actions .buy-btn{padding:10px 6px}
.faq details{background:var(--sf-surface);border-color:var(--sf-border);color:var(--sf-text);padding:20px;border-radius:8px}.faq p{color:var(--sf-muted)}.social-proof{display:none}.contact{margin-top:48px;background:var(--sf-surface);border-top:1px solid var(--sf-border)}.contact-box{border:0;border-radius:0;background:transparent;padding:20px 0}.contact-box h2{color:var(--sf-text);font-size:24px}.contact-box p,.footer-meta{color:var(--sf-muted)}.floating-cart{background:var(--sf-text);color:var(--sf-bg);border:0;border-radius:8px;min-height:52px}.drawer,.modal-card{border-radius:8px}.modal-body h2{font-size:28px;line-height:1.25;overflow-wrap:anywhere}.modal-media,.modal-media img.logo-img{background:var(--sf-surface)}.modal-media img{object-fit:contain}.modal-benefits li{border-radius:6px}.empty-search{color:var(--sf-muted)}.toast{max-width:calc(100% - 32px);font-size:13px;border-radius:8px}
body[data-theme="market"] .retail-hero{min-height:300px}body[data-theme="market"] .retail-layout{min-height:300px}body[data-theme="market"] .retail-copy h1{font-size:44px}body[data-theme="aurora"] .storefront-header{border-top:3px solid var(--sf-accent)}body[data-theme="obsidian"] .media{background:#f1f2f4}body[data-theme="obsidian"] .media img.logo-img{background:#f1f2f4}
@media(min-width:1600px){.retail-layout{min-height:420px;padding:52px 0}}
@media(max-width:1040px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}.storefront-search{max-width:380px}}
@media(max-width:760px){.wrap{width:calc(100% - 32px)}.storefront-search{order:4;flex-basis:100%;max-width:none}.storefront-nav{gap:12px;min-height:70px}.storefront-brand strong{font-size:18px;max-width:190px}.storefront-nav-cta{font-size:12px;padding:10px}.retail-layout,.retail-hero{min-height:340px}.retail-layout{padding:28px 0}.retail-copy h1,body[data-theme="market"] .retail-copy h1{font-size:36px}.retail-copy p{font-size:14px}.hero-art{object-position:60% center}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.benefit-row{grid-template-columns:repeat(2,minmax(0,1fr))}.benefit-row div{padding:14px 10px 14px 36px}.benefit-icon{left:7px;top:15px}.benefit-row span{font-size:11px}.section-title{display:block}.section-title h2{font-size:23px;margin-bottom:8px}.strip-head p{display:none}.card-body{padding:12px}.card h3{font-size:13px;min-height:40px}.card p{display:none}.media img.logo-img{padding:10px}.buy-row strong{font-size:20px}.card-actions{grid-template-columns:1fr}.card-actions .secondary-btn{min-height:32px;padding:5px}.card-actions .buy-btn{min-height:40px}.collection-tile{flex-basis:215px}.modal-card{grid-template-columns:1fr}.modal-media,.modal-media img{min-height:0;height:240px}.modal-body{padding:20px}.modal-actions{width:100%}.modal-actions button{flex:1}.contact-box .cta{margin-top:16px}.footer-meta{padding-bottom:64px}.floating-cart{bottom:max(12px,env(safe-area-inset-bottom));left:16px;right:16px}.retail-actions .secondary-btn{font-size:12px}.retail-actions .cta{font-size:13px}}
.collection-tile small{color:var(--sf-text)}.drawer:not(.open){visibility:hidden;box-shadow:none}.drawer.open{visibility:visible}.contact-box .cta{border-radius:6px;box-shadow:none}.benefit-icon{color:var(--sf-text)}.retail-copy h1{width:fit-content;max-width:100%;text-shadow:0 2px 8px #000,0 0 24px #000}.hero-art{opacity:.65}
body[data-theme="vice"]{--sf-bg:#000000;--sf-text:#ffffff;--sf-muted:#b5b5b5;--sf-border:#292929;--sf-surface:#101010;--sf-card:#101010;--sf-accent:#ef78b7;--sf-accent-text:#28102e}
body[data-theme="vice"] .storefront-header{border-top:2px solid #63ded9;background:#000000}
body[data-theme="vice"] .offer-bar{background:#ef78b7;color:#28102e}
body[data-theme="vice"] .storefront-brand strong{font-style:italic;color:#fff3fa}
body[data-theme="vice"] .retail-hero{border-bottom:3px solid #63ded9;background:#000000}
body[data-theme="vice"] .hero-art{opacity:.65}
body[data-theme="vice"] .retail-copy h1{font-style:italic;text-shadow:3px 3px 0 #9d306b,0 3px 18px #000000;font-weight:900}
body[data-theme="vice"] .retail-kicker{background:#63ded9;color:#142832}
body[data-theme="vice"] .retail-copy p{border-color:#63ded9;background:#000000d9}
body[data-theme="vice"] .cta,body[data-theme="vice"] .buy-btn{box-shadow:0 4px 0 #8d3264;transition:transform .2s,box-shadow .2s}
body[data-theme="vice"] .cta:hover,body[data-theme="vice"] .buy-btn:hover{transform:translateY(-2px);box-shadow:0 6px 0 #8d3264}
body[data-theme="vice"] .benefit-icon,body[data-theme="vice"] .collection-tile small{color:#63ded9}
body[data-theme="vice"] .media,body[data-theme="vice"] .media img.logo-img{background:#f9edf5}
body[data-theme="vice"] .card:hover{border-color:#63ded9;box-shadow:0 12px 30px #ef78b720}
body[data-theme="vice"] .section-title h2{border-left:3px solid #ef78b7;padding-left:12px}
body[data-theme="vice"] .floating-cart{background:#63ded9;color:#142832}
body[data-theme="vice"] .cart-badge{background:#000000;color:#ffffff}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*:before,*:after{transition:none!important;animation:none!important}}
`;
