create table if not exists public.storefy_workspaces (
  user_id uuid primary key references auth.users(id) on delete cascade,
  products jsonb not null default '[]'::jsonb,
  sites jsonb not null default '[]'::jsonb,
  active_site_id text,
  updated_at timestamptz not null default now()
);

alter table public.storefy_workspaces enable row level security;

drop policy if exists "storefy_workspaces_select_own" on public.storefy_workspaces;
create policy "storefy_workspaces_select_own"
on public.storefy_workspaces
for select
using (auth.uid() = user_id);

drop policy if exists "storefy_workspaces_insert_own" on public.storefy_workspaces;
create policy "storefy_workspaces_insert_own"
on public.storefy_workspaces
for insert
with check (auth.uid() = user_id);

drop policy if exists "storefy_workspaces_update_own" on public.storefy_workspaces;
create policy "storefy_workspaces_update_own"
on public.storefy_workspaces
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.storefy_public_stores (
  slug text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  store_config jsonb not null,
  products jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.storefy_public_stores enable row level security;

drop policy if exists "storefy_public_stores_select_public" on public.storefy_public_stores;
create policy "storefy_public_stores_select_public"
on public.storefy_public_stores
for select
using (true);

drop policy if exists "storefy_public_stores_insert_own" on public.storefy_public_stores;
create policy "storefy_public_stores_insert_own"
on public.storefy_public_stores
for insert
with check (auth.uid() = user_id);

drop policy if exists "storefy_public_stores_update_own" on public.storefy_public_stores;
create policy "storefy_public_stores_update_own"
on public.storefy_public_stores
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.storefy_user_integrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  encrypted_token text not null,
  token_iv text not null,
  token_tag text not null,
  token_last4 text not null,
  account_email text,
  account_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);

alter table public.storefy_user_integrations enable row level security;

drop policy if exists "storefy_user_integrations_no_client_select" on public.storefy_user_integrations;
drop policy if exists "storefy_user_integrations_no_client_insert" on public.storefy_user_integrations;
drop policy if exists "storefy_user_integrations_no_client_update" on public.storefy_user_integrations;
drop policy if exists "storefy_user_integrations_no_client_delete" on public.storefy_user_integrations;

-- Niveis, perfis e codigos de convite.
create table if not exists public.storefy_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nome varchar(120) not null default '',
  nivel int not null default 1 check (nivel in (1, 10)),
  codigo_socio varchar(32),
  is_admin boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.codigos_convite (
  id bigint generated by default as identity primary key,
  codigo varchar(32) not null unique,
  usos int not null default 0 check (usos >= 0),
  max_usos int not null default 5 check (max_usos > 0),
  status varchar(16) not null default 'ativo' check (status in ('ativo', 'expirado')),
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  expira_em timestamptz,
  check (usos <= max_usos)
);

create index if not exists codigos_convite_codigo_idx on public.codigos_convite(codigo);
create index if not exists storefy_profiles_codigo_socio_idx on public.storefy_profiles(codigo_socio);

alter table public.storefy_profiles enable row level security;
alter table public.codigos_convite enable row level security;

-- Niveis e codigos nunca sao alterados diretamente pelo navegador.
drop policy if exists "storefy_profiles_no_client_write" on public.storefy_profiles;
drop policy if exists "codigos_convite_no_client_access" on public.codigos_convite;

create or replace function public.storefy_create_default_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.storefy_profiles (user_id, nome, nivel)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1), 'Usuario'), 1)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists storefy_auth_user_profile on auth.users;
create trigger storefy_auth_user_profile
after insert on auth.users
for each row execute function public.storefy_create_default_profile();

insert into public.storefy_profiles (user_id, nome, nivel)
select id, coalesce(raw_user_meta_data->>'display_name', split_part(email, '@', 1), 'Usuario'), 1
from auth.users
on conflict (user_id) do nothing;

-- Na primeira instalacao, a conta mais antiga vira o administrador inicial.
do $$
begin
  if not exists (select 1 from public.storefy_profiles where is_admin) then
    update public.storefy_profiles
    set is_admin = true, nivel = 10, atualizado_em = now()
    where user_id = (select id from auth.users order by created_at asc limit 1);
  end if;
end;
$$;

create or replace function public.storefy_register_profile(p_user_id uuid, p_nome text, p_codigo text default null)
returns table (user_id uuid, nivel int, codigo_socio varchar)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_codigo varchar(32) := nullif(upper(trim(coalesce(p_codigo, ''))), '');
  v_convite public.codigos_convite%rowtype;
begin
  if v_codigo is null then
    insert into public.storefy_profiles (user_id, nome, nivel, codigo_socio)
    values (p_user_id, trim(p_nome), 1, null)
    on conflict (user_id) do update set nome = excluded.nome, nivel = 1, codigo_socio = null, atualizado_em = now();
  else
    select * into v_convite
    from public.codigos_convite
    where codigo = v_codigo
      and status = 'ativo'
      and usos < max_usos
      and (expira_em is null or expira_em > now())
    for update;

    if not found then raise exception 'Codigo invalido ou expirado'; end if;

    update public.codigos_convite
    set usos = usos + 1,
        status = case when usos + 1 >= max_usos then 'expirado' else status end
    where id = v_convite.id;

    insert into public.storefy_profiles (user_id, nome, nivel, codigo_socio)
    values (p_user_id, trim(p_nome), 10, v_codigo)
    on conflict (user_id) do update set nome = excluded.nome, nivel = 10, codigo_socio = v_codigo, atualizado_em = now();
  end if;

  return query select p.user_id, p.nivel, p.codigo_socio from public.storefy_profiles p where p.user_id = p_user_id;
end;
$$;

revoke all on function public.storefy_register_profile(uuid, text, text) from public, anon, authenticated;
grant execute on function public.storefy_register_profile(uuid, text, text) to service_role;

-- Depois de executar, promova seu usuario administrador uma vez:
-- update public.storefy_profiles set is_admin = true, nivel = 10
-- where user_id = (select id from auth.users where email = 'SEU_EMAIL');

create or replace function public.storefy_redeem_code(p_user_id uuid, p_codigo text)
returns table (user_id uuid, nivel int, codigo_socio varchar)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_codigo varchar(32) := nullif(upper(trim(coalesce(p_codigo, ''))), '');
  v_profile public.storefy_profiles%rowtype;
  v_convite public.codigos_convite%rowtype;
begin
  select * into v_profile from public.storefy_profiles where storefy_profiles.user_id = p_user_id for update;
  if not found then raise exception 'Perfil nao encontrado'; end if;
  if v_profile.nivel = 10 then
    return query select v_profile.user_id, v_profile.nivel, v_profile.codigo_socio;
    return;
  end if;
  select * into v_convite from public.codigos_convite
  where codigo = v_codigo and status = 'ativo' and usos < max_usos
    and (expira_em is null or expira_em > now()) for update;
  if not found then raise exception 'Codigo invalido ou expirado'; end if;
  update public.codigos_convite set usos = usos + 1, status = case when usos + 1 >= max_usos then 'expirado' else status end where id = v_convite.id;
  update public.storefy_profiles set nivel = 10, codigo_socio = v_codigo, atualizado_em = now() where storefy_profiles.user_id = p_user_id returning * into v_profile;
  return query select v_profile.user_id, v_profile.nivel, v_profile.codigo_socio;
end;
$$;
revoke all on function public.storefy_redeem_code(uuid, text) from public, anon, authenticated;
grant execute on function public.storefy_redeem_code(uuid, text) to service_role;